# Generated by Django 3.1.7 on 2021-04-03 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20210403_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benchresource',
            name='contractedtocompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contractedto', to='company.company'),
        ),
        migrations.AlterField(
            model_name='benchresource',
            name='employedtocompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employedto', to='company.company'),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
    ]
